[workspace]
members = [
	"asset-registry",
	"auction",
	"authority",
	"bencher",
	"benchmarking",
	"currencies",
	"gradually-update",
	"oracle",
	"oracle/rpc",
	"oracle/rpc/runtime-api",
	"tokens",
	"traits",
	"utilities",
	"vesting",
	"rewards",
	"nft",
	"xcm",
	"xtokens",
	"xcm-support",
	"unknown-tokens",
	"build-script-utils",
	"weight-gen",
	"weight-meter",
	"payments"
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[patch.'https://github.com/paritytech/substrate']
frame-benchmarking = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
frame-support = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
frame-system = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
pallet-authority-discovery = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
pallet-authorship = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
pallet-babe = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
pallet-balances = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
pallet-elections-phragmen = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
pallet-scheduler = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
pallet-session = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
pallet-staking = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
pallet-timestamp = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
pallet-treasury = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
pallet-vesting = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
pallet-transaction-payment = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sc-client-api = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sc-client-db = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sc-executor = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sc-executor-common = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sc-executor-wasmi = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sc-utils = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-api = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-application-crypto = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-arithmetic = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-authority-discovery = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-authorship = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-blockchain = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-consensus = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-consensus-slots = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-core = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-debug-derive = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-externalities = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-inherents = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-io = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-keystore = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-npos-elections = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-panic-handler = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-runtime = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-runtime-interface = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-session = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-staking = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-state-machine = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-std = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-storage = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-tasks = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-timestamp = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-trie = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-version = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-wasm-interface = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-tracing = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }
sp-maybe-compressed-blob = { git = "https://github.com/paritytech//substrate", rev = "3348e144f0a2b39ce08bd8e3b976c42fe0c990b9" }

[patch.'https://github.com/paritytech/cumulus']
cumulus-primitives-core = { git = "https://github.com/paritytech//cumulus", rev = "390042a01940a0a4d0b28eb196a2e9251f3cec33" }
cumulus-pallet-dmp-queue = { git = "https://github.com/paritytech//cumulus", rev = "390042a01940a0a4d0b28eb196a2e9251f3cec33" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/paritytech//cumulus", rev = "390042a01940a0a4d0b28eb196a2e9251f3cec33" }
cumulus-pallet-xcm = { git = "https://github.com/paritytech//cumulus", rev = "390042a01940a0a4d0b28eb196a2e9251f3cec33" }
parachain-info = { git = "https://github.com/paritytech//cumulus", rev = "390042a01940a0a4d0b28eb196a2e9251f3cec33" }

[patch.'https://github.com/paritytech/polkadot']
pallet-xcm = { git = "https://github.com/paritytech//polkadot", rev = "5174e9ae75b6843ecc460dfaa15f5851230638b8" }
polkadot-core-primitives = { git = "https://github.com/paritytech//polkadot", rev = "5174e9ae75b6843ecc460dfaa15f5851230638b8" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech//polkadot", rev = "5174e9ae75b6843ecc460dfaa15f5851230638b8" }
polkadot-parachain = { git = "https://github.com/paritytech//polkadot", rev = "5174e9ae75b6843ecc460dfaa15f5851230638b8" }
polkadot-primitives = { git = "https://github.com/paritytech//polkadot", rev = "5174e9ae75b6843ecc460dfaa15f5851230638b8" }
xcm = { git = "https://github.com/paritytech//polkadot", rev = "5174e9ae75b6843ecc460dfaa15f5851230638b8" }
xcm-executor = { git = "https://github.com/paritytech//polkadot", rev = "5174e9ae75b6843ecc460dfaa15f5851230638b8" }
xcm-builder = { git = "https://github.com/paritytech//polkadot", rev = "5174e9ae75b6843ecc460dfaa15f5851230638b8" }
xcm-simulator = { git = "https://github.com/paritytech//polkadot", rev = "5174e9ae75b6843ecc460dfaa15f5851230638b8" }
